### ISSUE TITLE
Open and focus inputfield according to GET parameter

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#315] opened 2019-07-01 03:33 UTC
### Short description of the enhancement

Now that we have the `InputfieldFocus()` function in `inputfields.js` it would be a nice enhancement if we could specify an inputfield ID to open and focus as part of the URL.

Examples:
```
/processwire/page/edit/?id=1&focus=Inputfield_headline
/processwire/setup/field/edit?id=117&focus=Inputfield_minlength
```

**Comment by jmartsch** [comment] 2019-07-01 09:08
Duplicate of https://github.com/processwire/processwire-requests/issues/236

**Closed as completed** 2019-07-01 09:22 UTC
