### ISSUE TITLE
Page List Select Multiple Quickly

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-requests#339] opened 2019-10-29 09:41 UTC
Hey @ryancramerdesign what do you think of making page list select multiple work like this module by RobinS by default:

https://processwire.com/talk/topic/22478-page-list-select-multiple-quickly

I don't think that we should need a module for that, or do you see any drawbacks with that implementation?

Thx

**Comment by jmartsch** [comment] 2019-10-29 10:21
Also thought, that this would be a good addition to the core +1

**Comment by teppokoivula** [comment] 2019-10-29 10:26
Could be an option of course, but I prefer this behaviour as well.

**Comment by BernhardBaumrock** [comment] 2019-10-29 10:45
Yeah, always good to have options :) Best would be Robin's version by default and an option for the old concept (simple checkbox in the settings)

**Comment by ryancramerdesign** [comment] 2021-02-19 17:43
@BernhardBaumrock Yes, I think this makes a lot of sense. Unless I'm missing something, I don't see any drawbacks. 

@Toutouwai Since you've already coded this, can we use what you've already done? I'm not positive how to implement it. Thanks.

**Comment by Toutouwai** [comment] 2021-02-22 01:01
> Since you've already coded this, can we use what you've already done? I'm not positive how to implement it.

@ryancramerdesign, you're welcome to use any part of my module code, but I don't think it should be added to the core as-is because there are hacky things in it like hiding the original select buttons and adding replacements. I think some of this hackiness was necessary due to event propagation issues caused by `return false` in core JS: https://github.com/processwire/processwire-issues/issues/1028

There are comments in my module code so it should be fairly clear how it works and I'm sure you'll be able to make it lot cleaner if you are integrating it into the core.

**Comment by ryancramerdesign** [comment] 2022-03-25 17:35
Thanks @BernhardBaumrock @Toutouwai I have added this

**Comment by jmartsch** [comment] 2022-09-12 16:11
@BernhardBaumrock  As this is completed I recommend closing the issue so it doesn't clutter up the request list.

**Closed as completed** 2022-09-12 16:14 UTC
Labels: enhancement, completed
